### PR TITLE
Feature/i18n

### PR DESCRIPTION
**Pull request by hamicakir**
Internalization added project.

### CODE REVIEW

**Comment by SelmanKahya** [comment]
here is what we can do to have a more lightweight solution:

- copy [language-detector](https://github.com/i18next/i18next-express-middleware/blob/master/src/languageLookups/header.js) code that looks for the header 
- put it in a middleware
- update our server-rendering route to detect language and load proper json file on server
- and send the translation file only for 1 language (which is user's language)

Right now, by doing `import i18n from '@/configs/i18n';` and inside `import LANG from '@/translations/LANG.json';`, you are importing whole translated strings onto client and it will drastically increase the bundle size.

**Comment by SelmanKahya** [comment]
@hamicakir thoughts?

**Comment by SelmanKahya** [comment]
any updates?

**Comment by hamicakir** [comment]
I will complete this task tomorrow.

**Comment by SelmanKahya** [comment]
@hamicakir any updates on this? otherwise, @trkaplan can take this on.

**Comment by SelmanKahya** [comment]
@hamicakir closing due to inactivity. see https://github.com/Kommunity-app/kommunity-frontend/issues/4

**Pull request closed without merging**
